# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Orchestrate or schedule a set of jobs
jobs:
  test-unit:
    docker:
      - image: circleci/node:10
    working_directory: ~/simple-quote
    steps:
      # Get code from git
      - checkout
      # Make sure we are up to date with the package.json dependencies
      - run: yarn install
      # Run some tests
      - run:
          name: Run Tests
          command: yarn test
  deploy:
    machine:
        enabled: true
    working_directory: ~/simple-quote
    environment:
      HEROKU_APP: "$HEROKU_APP_NAME"
    steps:
      # Get code from git
      - checkout
      - run:
          name: Setup Heroku
          command: bash .circleci/setup-heroku.sh
      - run:
          name: Deploy main to Heroku
          command: |
            git push heroku sequential-branch-filter:main
            heroku run yarn install
            sleep 5
            heroku restart
workflows:
  version: 2
  build-deploy:
    jobs:
      - test-unit
      - deploy:
        # only run deploy-via-git job if the test-unit job has completed
          requires:
            - test-unit
          filters:
            # only run deploy-via-git job on main branch
            branches:
              only: main
