# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Orchestrate or schedule a set of jobs
jobs:
  test-unit:
    docker:
      - image: circleci/node:10
    steps:
      # Get code from git
      - checkout
      # Make sure we are up to date with the package.json dependencies
      - run: yarn install
      # Run some tests
      - run:
          name: Run Tests
          command: yarn test
  build:
    docker:
      - image: circleci/node:10
    steps:
      # Get code from git
      - checkout
      # Make sure we are up to date with the package.json dependencies
      - run: yarn install
      # Run some tests
      - run:
          name: Run App
          command: yarn start
  deploy:
    docker:
      - image: circleci/node:10
    steps:
      # Get code from git
      - checkout
      # Make sure we are up to date with the package.json dependencies
      - run:
          name: Deploy main to Heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git main
            yarn start
workflows:
  version: 2
  build-deploy:
    jobs:
      - test-unit
      - build
      - deploy:
        # only run deploy-via-git job if the test-unit & build job has completed
          requires:
            - test-unit
            - build
          filters:
            branches:
              only: main # only run deploy-via-git job on main branch
